---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUblF5cUK96+8JIV8U71f9cRkOvIMwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMTcyOTAwWhcNMjQxMTE4MTcyOTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AM75gKIEwercmjLWuDay+dEhc4QlNFqklC+BvWdyYG5AnLeINEgIcruQYI/BZBJt
    B7ZRM/OxWQH1T9tXyVNqt1JrK5V1iO/kPRgaAMvcdDAIcePeGzGK/bGDgqljD8Tr
    QWOudr0Rb8J9KysmGm9XwtL0RWvOjRWbDSZVYGIbbSeEeORrMx2/2uIsvd2v/J3t
    lRAzGrqqotPYEZeH0vw0zr1DOZN/fwVfp0EpRQ1KHTq1jSsrDorIIH+84T2Xk8qa
    fLo4Gco3+1FbVME4nGSkTzybRsgWFOLNxvZphwwqsDR3noK8t1qYRuTfyE/d4nNp
    2r+Z5+tz+8KgRWF+74OoQ2JJVZgwwFK+5aqyT/t9mqzpLRW7mQT7TkhoFqwi4y+L
    G05Jl6S7S5swxglnR9k5e4nunTWYVxlEcQlLkSVn1AsA2eItOQmuaG4n2Gw3UgFF
    uHqzQR7avU2jV3tole7UBrIL42WBMH/XjCjoCiTjPqJmsmWlt5VOa0O7gKR5esE2
    QD6SLrGA23lEQzsaxKGr/iYXbgsQLvfWVHPgaay3wm3EQESEgeWCJlUbp61HjQ4q
    TihoHkFQS/ixmYmUxq526ti6Y2yn8nkaLiiceAWAOeMeu+OQo3JzItqzTHDjOx7V
    oI1/IbDC/TfoW4QJKfXPwiBKxjHyCb2fZSo9EdVBJicJAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSr3eus/70ZJhWI
    Q41FFuNeBz9z7zANBgkqhkiG9w0BAQ0FAAOCAgEAzAdtJS2rLtKadxKiDGJsLGCf
    vL7HJJtbSYW1vmTT4GaP4R+2rmT/DKGTV3GHBdqNd1H+RHNV1d/MZJwt6/VzQkMD
    XyTeX2z/xyAz3yWojWidIB7XFT2JOItBi0ilZQHpNDrfig/BUGlkv0OAXHIS3X4Q
    Y2eT04g7m9PowGiL4rEZg+MVr2l4sUq2CEFDMkoXnMs7j+em1WbUjbOTauxiDNGt
    nvTqb4FTMGcSpY60pxY6lSOn30CC0IeWQXzDQVRjy+NvkMeKr5/YdYdFgIyjKSrh
    P6Xjgb4Bhk2JqBnsby918pvKH3kdDupZr3WV9N1PDyXYg7u0QW7aea0eimWe3y+a
    Zu/i8f/GTVqyIYK1OmJ4d8djb5JyBQz72370CbCXE/nvh3y74V1M8aMF864tD3Ot
    15Kk7l+g8kynbehZTB/X0K0GI4ZBRZBbBHQvPxBQe3AJmpdKNKLMeInbfwBfe37+
    BiLdU4ijQgWEBrYlsGp+IKicjL9YP4EtYYN6ruS/bxxkINEYVBEPyxrfwuWJPyOr
    JKbylv1tDiYIqlzCnJgPGXGbRXaR62lURa6xvQ0rUEEvVW0M4kHgp1rYKErhuybq
    etGMlGc4ERPAtwzYlbKSTWlexYt1vptlpjnlHytJttX/zKP32Nqk8relRk0Adade
    FYjudgftEOOwMe5OC68=
    -----END CERTIFICATE-----
    
